"""empty message

Revision ID: 01d93a813d34
Revises: 5f04a86f03ca
Create Date: 2024-07-17 22:38:32.038153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d93a813d34'
down_revision = '5f04a86f03ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.SmallInteger(), nullable=True))
        batch_op.drop_column('num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num', sa.SMALLINT(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
