"""empty message

Revision ID: 17f60d5f1d96
Revises: 06a25d0582f7
Create Date: 2024-07-19 12:26:10.056780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f60d5f1d96'
down_revision = '06a25d0582f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.drop_column('about')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.TEXT(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
