"""empty message

Revision ID: 5f04a86f03ca
Revises: 7fa19ef2c39a
Create Date: 2024-07-17 22:36:15.210498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f04a86f03ca'
down_revision = '7fa19ef2c39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num', sa.SmallInteger(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.SMALLINT(), nullable=True))
        batch_op.drop_column('num')

    # ### end Alembic commands ###
