"""empty message

Revision ID: 87617e793175
Revises: f99f5eda2a33
Create Date: 2024-07-20 00:36:00.036564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87617e793175'
down_revision = 'f99f5eda2a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profileimage')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_img', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_img')
        batch_op.drop_column('profile_img')

    op.create_table('profileimage',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'image_id')
    )
    # ### end Alembic commands ###
